name: Release to Maven Central

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    if: github.repository == 'yamilmedina/natural-kron'
    name: Release to maven central
    runs-on: ubuntu-latest
    environment: sonatype
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Gradle Setup
        uses: gradle/actions/setup-gradle@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Publish Artifact
        uses: gradle/gradle-build-action@v3
        with:
          arguments: "publishAndReleaseToMavenCentral --no-configuration-cache"
        env:
          IS_RELEASE: true
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.PGP_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.PGP_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.PGP_PASSPHRASE }}
